

POST http://127.0.0.1:8000/api/auth/send-otp/
Content-Type: application/json

{"phone_number":"01303206223"}
###


POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{ "phone_number":"01303206223", "otp":"379814", "password" : "4321" }
###


POST http://127.0.0.1:8000/api/auth/token/refresh/
Content-Type: application/json

{ "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNDI2MjI3NCwiaWF0IjoxNzAzNDE3NDc0LCJqdGkiOiIzNTc2YTRlZWQ1MzQ0ODdkOTc2MDZiMDcwMzUwMDE1NiIsInVzZXJfaWQiOiIwMTMwMzIwNjIyMyJ9.G4ye8V5OrliPGXOiWOzIOPNAgFvSvc0VilhteSgvl_A" }
###

GET http://127.0.0.1:8000/api/auth/get-user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAzNDE4MTM0LCJpYXQiOjE3MDM0MTc0NzQsImp0aSI6IjU0NDIyNDFiZDQxZTRkZDg4NTgyOTEwODA5NzI2MGIwIiwidXNlcl9pZCI6IjAxMzAzMjA2MjIzIn0.G2qPAFJm95hBbW2-d7Ve04UTsTY7QM32bPAG3E3dP54
###