# Generated by Django 4.1 on 2024-02-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_buy_price',
            new_name='product_base_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_count',
            new_name='product_sale_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sell_price',
            new_name='product_selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_in_stock',
            new_name='product_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='visit_count',
            new_name='product_visit_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wishlist_count',
            new_name='product_wishlist_count',
        ),
    ]
