# Generated by Django 4.1 on 2024-02-25 13:47

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_buy_price_product_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=product.models.Product.generate_unique_product_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
