# Generated by Django 4.1 on 2024-03-17 08:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='id',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_id',
            field=models.CharField(default=product.models.generate_unique_id, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_order',
            field=models.IntegerField(default=0),
        ),
    ]
