# Generated by Django 4.1 on 2024-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productimage_id_productimage_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
