# Generated by Django 4.1 on 2024-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_image_blurhash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
