# Generated by Django 4.1 on 2024-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_profile_image_blurhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
