# Generated by Django 4.1 on 2024-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='two_in_a_row',
            field=models.BooleanField(default=False),
        ),
    ]
