# Generated by Django 4.1 on 2024-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_two_in_a_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='two_in_a_row',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='two_in_a_row',
            field=models.BooleanField(default=False),
        ),
    ]
