# Generated by Django 4.1 on 2024-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_two_in_a_row_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartproduct',
            name='unique_cart',
        ),
        migrations.RemoveIndex(
            model_name='cartproduct',
            name='product_car_product_ee8178_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartproduct',
            name='product_car_user_id_11d69f_idx',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('product', 'user', 'size'), name='unique_cart'),
        ),
    ]
