# Generated by Django 4.1 on 2024-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_cartproduct_unique_cart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartproduct',
            name='unique_cart',
        ),
        migrations.RemoveConstraint(
            model_name='wishlistproduct',
            name='unique_wishlist',
        ),
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('product', 'user', 'size'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='wishlistproduct',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_wishlist_product'),
        ),
    ]
