# Generated by Django 4.1 on 2023-11-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('photo_url', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_picture_url', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(max_length=255)),
                ('sms_notify', models.BooleanField()),
                ('email_notify', models.BooleanField()),
                ('app_notify', models.BooleanField()),
                ('notification_frequency_day', models.IntegerField()),
                ('sms_frequency_day', models.IntegerField()),
                ('expire_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.IntegerField(choices=[(0, 'Flat Discount'), (1, 'Clearance Sale'), (2, 'Free Delivery'), (3, 'Trusted Customer Deal'), (4, 'Lucky Customer Deal')])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_picture_url', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(max_length=255)),
                ('sms_notify', models.BooleanField()),
                ('email_notify', models.BooleanField()),
                ('app_notify', models.BooleanField()),
                ('notification_frequency_day', models.IntegerField()),
                ('sms_frequency_day', models.IntegerField()),
                ('duration_day', models.IntegerField()),
                ('promo_code', models.CharField(max_length=50)),
                ('minimum_purchase', models.IntegerField()),
                ('DiscountPercentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type'], name='marketing_o_offer_t_0fb858_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['title'], name='marketing_o_title_5e3723_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['duration_day'], name='marketing_o_duratio_af8f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['promo_code'], name='marketing_o_promo_c_f664f5_idx'),
        ),
        migrations.AddField(
            model_name='notificationproduct',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.notification'),
        ),
        migrations.AddField(
            model_name='notificationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['title'], name='marketing_n_title_086413_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expire_on'], name='marketing_n_expire__738e49_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['title'], name='marketing_b_title_480705_idx'),
        ),
        migrations.AddIndex(
            model_name='offerproduct',
            index=models.Index(fields=['offer'], name='marketing_o_offer_i_d17b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='offerproduct',
            index=models.Index(fields=['product'], name='marketing_o_product_7da5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationproduct',
            index=models.Index(fields=['notification'], name='marketing_n_notific_6d1e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationproduct',
            index=models.Index(fields=['product'], name='marketing_n_product_a49a60_idx'),
        ),
    ]
