# Generated by Django 4.1 on 2024-02-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_order',
            field=models.IntegerField(default=0),
        ),
    ]
