# Generated by Django 4.1 on 2024-05-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_banner_banner_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='DiscountPercentage',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.IntegerField(choices=[(0, 'Percentage'), (1, 'Fixed')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.IntegerField(choices=[(0, 'Flat Discount'), (1, 'Clearance Sale'), (2, 'Free Delivery'), (3, 'Promo Code')]),
        ),
    ]
