# Generated by Django 4.1 on 2024-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_offer_minimum_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration_day',
            field=models.DateTimeField(),
        ),
    ]
