# Generated by Django 4.1 on 2024-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_offer_duration_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
