# Generated by Django 4.1 on 2023-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_87acce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['staff_level'], name='authenticat_staff_l_03a9da_idx'),
        ),
    ]
