# Generated by Django 4.1 on 2023-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_picture_url', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_picture_url', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('withdraw_amount', models.PositiveIntegerField()),
                ('document_picture_url', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentWithdrawApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestorShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('share_amount', models.PositiveIntegerField()),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfitShareRecived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=155)),
                ('share_amount', models.PositiveIntegerField()),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('designation', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('work_day', models.PositiveIntegerField()),
                ('salary_amount', models.PositiveIntegerField()),
                ('is_approved', models.BooleanField()),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
            ],
        ),
    ]
