# Generated by Django 4.1 on 2023-12-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryapproval',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.salary'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='reporting_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasephoto',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.purchase'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitsharerecived',
            name='profit_share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounce.profitshare'),
        ),
        migrations.AddField(
            model_name='profitsharerecived',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitshareapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitshareapproval',
            name='profit_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.profitshare'),
        ),
        migrations.AddField(
            model_name='profitshare',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorshare',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentwithdrawapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentwithdrawapproval',
            name='investment_withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.investmentwithdraw'),
        ),
        migrations.AddField(
            model_name='investmentwithdraw',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_withdraws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentwithdraw',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_investment_withdraws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentapproval',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountbalanceapproval',
            name='account_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounce.accountbalance'),
        ),
        migrations.AddField(
            model_name='accountbalanceapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
