# Generated by Django 4.1 on 2023-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('home_delivery_available', models.BooleanField()),
                ('pickup_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('courier_choice', models.IntegerField(choices=[(1, 'Pathao Courier'), (2, 'RedX Courier')])),
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourierStore',
            fields=[
                ('courier_choice', models.IntegerField(choices=[(1, 'Pathao Courier'), (2, 'RedX Courier')])),
                ('courier_store_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.city')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('courier_choice', models.IntegerField(choices=[(1, 'Pathao Courier'), (2, 'RedX Courier')])),
                ('products_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_quantity', models.PositiveBigIntegerField(default=1)),
                ('item_weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=10)),
                ('item_description', models.TextField()),
                ('delivery_instruction', models.TextField()),
                ('delivery_type', models.IntegerField(choices=[(48, 'Regular delivery'), (12, 'On Demand delivery')], default=48)),
                ('item_type', models.IntegerField(choices=[(1, 'Document Item'), (2, 'Parcel Item'), (3, 'Fragile Item')], default=2)),
                ('delivery_cost', models.PositiveBigIntegerField(default=0)),
                ('amount_to_collect', models.PositiveBigIntegerField(default=0)),
                ('delivery_consignment_id', models.CharField(max_length=255)),
                ('delivery_tracking_url', models.CharField(max_length=255)),
                ('payment_method', models.IntegerField(choices=[(1, 'Cash On Delivery'), (2, 'sslcommerz'), (3, 'bKash')], default=1)),
                ('order_status', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('courier_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.courierstore')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.area')),
                ('customer_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.city')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.city')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=10)),
                ('product_quantity', models.PositiveBigIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.zone'),
        ),
        migrations.AddField(
            model_name='courierstore',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.zone'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='order_city_name_11672e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['courier_choice'], name='order_city_courier_af9508_idx'),
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.zone'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['city'], name='order_zone_city_id_61fd41_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['name'], name='order_zone_name_d5d0be_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='order_revie_order_i_0b213f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='order_revie_product_ebde33_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='order_revie_is_appr_f6877d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernote',
            index=models.Index(fields=['order'], name='order_order_order_i_0b68dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernote',
            index=models.Index(fields=['title'], name='order_order_title_c8f94a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedproduct',
            index=models.Index(fields=['order'], name='order_order_order_i_67d54a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedproduct',
            index=models.Index(fields=['product'], name='order_order_product_fe5e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='order_order_order_i_0faab6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_order_custome_df6711_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='order_order_order_s_54575a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_order_payment_6d88a5_idx'),
        ),
        migrations.AddIndex(
            model_name='courierstore',
            index=models.Index(fields=['courier_choice'], name='order_couri_courier_78103a_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['zone'], name='order_area_zone_id_442046_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['name'], name='order_area_name_57f772_idx'),
        ),
    ]
