# Generated by Django 4.1 on 2024-08-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_note_order_customer_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.AddField(
            model_name='order',
            name='order_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
    ]
