# Generated by Django 4.1 on 2024-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_products_value_remove_order_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_value',
            new_name='products_base_value',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='customers_delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='flat_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='products_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='products_regular_value',
            field=models.IntegerField(default=0),
        ),
    ]
