# Generated by Django 4.1 on 2024-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderedproduct',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_ordered_product'),
        ),
    ]
