# Generated by Django 4.1 on 2024-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_created_at_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
