# Generated by Django 4.1 on 2024-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderedproduct_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='size',
            field=models.CharField(default='XL', max_length=10),
            preserve_default=False,
        ),
    ]
