# Generated by Django 4.1 on 2024-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_review_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
