# Generated by Django 4.1 on 2024-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_review_description_alter_review_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='is_review_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
