# Generated by Django 4.1 on 2024-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderedproduct_is_review_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='is_review_approved',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='review_status',
            field=models.IntegerField(choices=[(1, 'Panding'), (2, 'Submitted'), (3, 'Approved')], default=1),
        ),
    ]
